### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by tassadarforaiur** [darkytoothpaste/keymapper#4]
attempting to compile in arduino software 1.6.3 on windows

**compiler output after fixing spi in settings.h for usb host 2.0**

string_644,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1377:1: error: 'string_645' was not declared in this scope
 string_645,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1378:1: error: 'string_646' was not declared in this scope
 string_646,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1379:1: error: 'string_647' was not declared in this scope
 string_647,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1380:1: error: 'string_648' was not declared in this scope
 string_648,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1381:1: error: 'string_649' was not declared in this scope
 string_649,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1382:1: error: 'string_650' was not declared in this scope
 string_650,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1383:1: error: 'string_651' was not declared in this scope
 string_651,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1384:1: error: 'string_652' was not declared in this scope
 string_652,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1385:1: error: 'string_653' was not declared in this scope
 string_653,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1386:1: error: 'string_654' was not declared in this scope
 string_654,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1387:1: error: 'string_655' was not declared in this scope
 string_655,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1388:1: error: 'string_656' was not declared in this scope
 string_656,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1389:1: error: 'string_657' was not declared in this scope
 string_657,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1390:1: error: 'string_658' was not declared in this scope
 string_658,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1391:1: error: 'string_659' was not declared in this scope
 string_659,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1392:1: error: 'string_660' was not declared in this scope
 string_660,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1393:1: error: 'string_661' was not declared in this scope
 string_661,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1394:1: error: 'string_662' was not declared in this scope
 string_662,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1395:1: error: 'string_663' was not declared in this scope
 string_663,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1396:1: error: 'string_664' was not declared in this scope
 string_664,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1397:1: error: 'string_665' was not declared in this scope
 string_665,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1398:1: error: 'string_666' was not declared in this scope
 string_666,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1399:1: error: 'string_667' was not declared in this scope
 string_667,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1400:1: error: 'string_668' was not declared in this scope
 string_668,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1401:1: error: 'string_669' was not declared in this scope
 string_669,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1402:1: error: 'string_670' was not declared in this scope
 string_670,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1403:1: error: 'string_671' was not declared in this scope
 string_671,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1404:1: error: 'string_672' was not declared in this scope
 string_672,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1405:1: error: 'string_673' was not declared in this scope
 string_673,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1406:1: error: 'string_674' was not declared in this scope
 string_674,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1407:1: error: 'string_675' was not declared in this scope
 string_675,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1408:1: error: 'string_676' was not declared in this scope
 string_676,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1409:1: error: 'string_677' was not declared in this scope
 string_677,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1410:1: error: 'string_678' was not declared in this scope
 string_678,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1411:1: error: 'string_679' was not declared in this scope
 string_679,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1412:1: error: 'string_680' was not declared in this scope
 string_680,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1413:1: error: 'string_681' was not declared in this scope
 string_681,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1414:1: error: 'string_682' was not declared in this scope
 string_682,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1415:1: error: 'string_683' was not declared in this scope
 string_683,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1416:1: error: 'string_684' was not declared in this scope
 string_684,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1417:1: error: 'string_685' was not declared in this scope
 string_685,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1418:1: error: 'string_686' was not declared in this scope
 string_686,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1419:1: error: 'string_687' was not declared in this scope
 string_687,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1420:1: error: 'string_688' was not declared in this scope
 string_688,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1421:1: error: 'string_689' was not declared in this scope
 string_689,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1422:1: error: 'string_690' was not declared in this scope
 string_690,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1423:1: error: 'string_691' was not declared in this scope
 string_691,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1424:1: error: 'string_692' was not declared in this scope
 string_692,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1425:1: error: 'string_693' was not declared in this scope
 string_693,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1426:1: error: 'string_694' was not declared in this scope
 string_694,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1427:1: error: 'string_695' was not declared in this scope
 string_695,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1428:1: error: 'string_696' was not declared in this scope
 string_696,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1429:1: error: 'string_697' was not declared in this scope
 string_697,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1430:1: error: 'string_698' was not declared in this scope
 string_698,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1431:1: error: 'string_699' was not declared in this scope
 string_699,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1432:1: error: 'string_700' was not declared in this scope
 string_700,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1433:1: error: 'string_701' was not declared in this scope
 string_701,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1434:1: error: 'string_702' was not declared in this scope
 string_702,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1435:1: error: 'string_703' was not declared in this scope
 string_703,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1436:1: error: 'string_704' was not declared in this scope
 string_704,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1437:1: error: 'string_705' was not declared in this scope
 string_705,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1438:1: error: 'string_706' was not declared in this scope
 string_706,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1439:1: error: 'string_707' was not declared in this scope
 string_707,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1440:1: error: 'string_708' was not declared in this scope
 string_708,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1441:1: error: 'string_709' was not declared in this scope
 string_709,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1442:1: error: 'string_710' was not declared in this scope
 string_710,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1443:1: error: 'string_711' was not declared in this scope
 string_711,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1444:1: error: 'string_712' was not declared in this scope
 string_712,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1445:1: error: 'string_713' was not declared in this scope
 string_713,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1446:1: error: 'string_714' was not declared in this scope
 string_714,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1447:1: error: 'string_715' was not declared in this scope
 string_715,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1448:1: error: 'string_716' was not declared in this scope
 string_716,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1449:1: error: 'string_717' was not declared in this scope
 string_717,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1450:1: error: 'string_718' was not declared in this scope
 string_718,
 ^
C:\Users\tassadarforaiur\Documents\Arduino\libraries\keymapper-o/keymapper_game.h:1451:1: error: 'string_719' was not declared in this scope
 string_719};
 ^
keymapper.ino:47:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:48:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:49:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:50:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:51:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:52:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:53:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:54:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:59:5: error: 'qwertyKeymap' was not declared in this scope
keymapper.ino:60:5: error: 'tarmak1Keymap' was not declared in this scope
keymapper.ino:61:5: error: 'tarmak2Keymap' was not declared in this scope
keymapper.ino:62:5: error: 'tarmak3Keymap' was not declared in this scope
keymapper.ino:63:5: error: 'tarmak4Keymap' was not declared in this scope
keymapper.ino:64:5: error: 'colemakKeymap' was not declared in this scope
keymapper.ino:65:5: error: 'dvorakKeymap' was not declared in this scope
keymapper.ino:66:5: error: 'workmanKeymap' was not declared in this scope
Multiple libraries were found for "Usb.h"
 Used: C:\Users\tassadarforaiur\Documents\Arduino\libraries\USB_Host_Shield_Library_2.0
 Not used: C:\Users\tassadarforaiur\Documents\Arduino\libraries\USBHost
Error compiling.

*_after commenting out every line that refers to the keymapper game, *_

keymapper.ino:47:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:48:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:49:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:50:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:51:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:52:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:53:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:54:9: error: 'prog_uint8_t' does not name a type
keymapper.ino:59:5: error: 'qwertyKeymap' was not declared in this scope
keymapper.ino:60:5: error: 'tarmak1Keymap' was not declared in this scope
keymapper.ino:61:5: error: 'tarmak2Keymap' was not declared in this scope
keymapper.ino:62:5: error: 'tarmak3Keymap' was not declared in this scope
keymapper.ino:63:5: error: 'tarmak4Keymap' was not declared in this scope
keymapper.ino:64:5: error: 'colemakKeymap' was not declared in this scope
keymapper.ino:65:5: error: 'dvorakKeymap' was not declared in this scope
keymapper.ino:66:5: error: 'workmanKeymap' was not declared in this scope
Multiple libraries were found for "Usb.h"
 Used: C:\Users\tassadarforaiur\Documents\Arduino\libraries\USB_Host_Shield_Library_2.0
 Not used: C:\Users\tassadarforaiur\Documents\Arduino\libraries\USBHost
Error compiling.

**Comment by nidusin** [comment]
This error is an issue with the older syntax for PROGMEM the keymapper uses which has been depricated in later versions of the arduino compiler. I have modified it for my own use so that it compiles fine and would be happy to submit it to the repo.

**Comment by gdsports** [comment]
@DreymaR @professor

I forked the repo and updated it to compile using Arduino IDE 1.8.5. I also added support for Teensy 3.6 USB Host. Teensy 3.6 requires soldering only 5 header pins for the USB host cable. The board also has lots of room for expansion with 1 MByte Flash and 256 KByte RAM.

https://github.com/gdsports/keymapper/

I am considering merging PR #3 but is there something better?

**Comment by DreymaR** [comment]
Nice work! Now, could you consider adding Teensy 3.6 support to TMK please?
That's what I'm using now. I don't know the technical details but
apparently it's about some libraries.

Teensy 3.6 seems really awesome, with all that memory one could have a lot
of functionality and hotstrings.

**Comment by gdsports** [comment]
I looked at TMK but it looks far more complex than I have time for. I just need something to try out colemak/tarmak.
